
		CREATE TABLE tokens (
			  date_modified DATE NULL ,
			  date_created DATE NULL ,
			  token_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
			  company_id INTEGER NULL,
			  loan_type_id INTEGER NULL,
			  token_name   varchar(50) not null,
			  value_array blob NOT NULL,
			  UNIQUE (company_id, loan_type_id, token_name)	ON CONFLICT FAIL);
  	
  				CREATE TABLE application (
			  date_modified DATE NULL,
			  date_created DATE NULL,
			  company_id INTEGER NULL,
			  application_id INTEGER NOT NULL PRIMARY KEY,
			  customer_id INTEGER NULL,
			  archive_db2_id INTEGER NULL,
			  archive_mysql_id INTEGER NULL,
			  archive_cashline_id INTEGER NULL,
			  login_id INTEGER NULL,
			  is_react varchar(5) NULL,
			  loan_type_id INTEGER NULL,
			  rule_set_id INTEGER NULL,
			  enterprise_site_id INTEGER NULL,
			  application_status_id INTEGER NULL,
			  date_application_status_set INTEGER NULL,
			  date_next_contact DATE NULL ,
			  ip_address varchar(40)  NULL ,
			  application_type varchar(40)  NULL,
			  bank_name varchar(100)  NULL ,
			  bank_aba varchar(9)  NULL ,
			  bank_account varchar(17)  NULL ,
			  bank_account_type varchar(40)  NULL,
			  date_fund_estimated DATE NULL,
			  date_fund_actual date NULL,
			  date_first_payment date  NULL,
			  fund_requested float NULL,
			  fund_qualified float NULL,
			  fund_actual float NULL,
			  finance_charge float NULL,
			  payment_total float NULL,
			  apr float NULL,
			  income_monthly float NULL,
			  income_source varchar(40)  NULL,
			  income_direct_deposit varchar(40)  NULL,
			  income_frequency varchar(40)  NULL,
			  income_date_soap_1 date NULL,
			  income_date_soap_2 date NULL,
			  paydate_model varchar(40)  NULL,
			  day_of_week varchar(40)  NULL,
			  last_paydate date NULL,
			  day_of_month_1 INTEGER NULL,
			  day_of_month_2 INTEGER NULL,
			  week_1 INTEGER NULL,
			  week_2 INTEGER NULL,
			  track_id varchar(40)  NULL,
			  agent_id INTEGER NULL,
			  agent_id_callcenter INTEGER NULL,
			  dob date NULL,
			  ssn varchar(9)  NULL ,
			  legal_id_number varchar(30) ,
			  legal_id_state varchar(2) ,
			  legal_id_type varchar(30) ,
			  identity_verified varchar(30) ,
			  email varchar(100) NULL,
			  email_verified varchar(30) NULL,
			  name_last varchar(30) NULL,
			  name_first varchar(30) NULL,
			  name_middle varchar(30) NULL,
			  name_suffix varchar(30) NULL,
			  street varchar(100)  NULL ,
			  unit varchar(10) NULL,
			  city varchar(30)  NULL ,
			  state varchar(30)  NULL,
			  county varchar(30) NULL,
			  zip_code varchar(30) NULL,
			  tenancy_type varchar(30) NULL,
			  phone_home varchar(30) NULL,
			  phone_cell varchar(30) NULL,
			  phone_fax varchar(30) NULL,
			  call_time_pref varchar(30) NULL,
			  contact_method_pref varchar(30) NULL,
			  marketing_contact_pref varchar(30) NULL,
			  employer_name varchar(100) NULL,
			  job_title varchar(100) NULL,
			  supervisor varchar(50) NULL,
			  shift varchar(100) NULL,
			  date_hire date  NULL,
			  job_tenure float  NULL,
			  phone_work varchar(10)  NULL,
			  phone_work_ext varchar(8)  NULL,
			  work_address_1 varchar(50)  NULL,
			  work_address_2 varchar(50)  NULL,
			  work_city varchar(30)  NULL,
			  work_state varchar(2)  NULL,
			  work_zip_code varchar(9)  NULL,
			  employment_verified varchar(30) NULL,
			  pwadvid varchar(30) NULL,
			  olp_process varchar(255) NULL,
			  is_watched varchar(30) NULL,
			  schedule_model_id INTEGER NULL,
			  modifying_agent_id INTEGER NULL,
			  banking_start_date date  NULL,
			  residence_start_date date  NULL,
			  cfe_rule_set_id INTEGER NULL
			  
			);
  		
		CREATE TABLE rule_component (
					  date_modified DATE NULL,
					  date_created DATE NULL,
					  active_status varchar(10) NULL,
					  rule_component_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
					  name varchar(100)  NULL ,
					  name_short varchar(30)  NULL,
					  grandfathering_enabled varchar(5)
					
					) ;	
					
		CREATE TABLE rule_component_parm (
					  date_modified DATE NULL,
					  date_created DATE NULL,
					  active_status varchar(10),
					  rule_component_parm_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
					  rule_component_id INTEGER  NULL,
					  parm_name varchar(30)  NULL ,
					  parm_subscript varchar(30) ,
					  sequence_no INTEGER ,
					  display_name varchar(50)  NULL ,
					  description varchar(255)  NULL ,
					  parm_type varchar(10),
					  user_configurable varchar(10),
					  input_type varchar(10),
					  presentation_type varchar(10),
					  value_label varchar(50) ,
					  subscript_label varchar(50) ,
					  value_min INTEGER ,
					  value_max INTEGER ,
					  value_increment INTEGER,
					  length_min INTEGER,
					  length_max INTEGER,
					  enum_values varchar(255) ,
					  preg_pattern varchar(255) ,
					  UNIQUE (rule_component_id,parm_name,parm_subscript)
					); 
		CREATE TABLE rule_set (
				  date_modified DATE NULL,
				  date_created DATE NULL,
				  active_status varchar(10),
				  rule_set_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
				  name varchar(100),
				  loan_type_id INTEGER,
				  date_effective DATE NULL,
				  UNIQUE (loan_type_id,date_effective)
				);
	
		CREATE TABLE rule_set_component (
				  date_modified DATE NULL,
				  date_created DATE NULL,
				  active_status varchar(10),
				  rule_set_id INTEGER,
				  rule_component_id INTEGER,
				  sequence_no INTEGER
				
				);
	
		CREATE TABLE rule_set_component_parm_value (
				  date_modified DATE NULL,
				  date_created DATE NULL,
				  agent_id INTEGER,
				  rule_set_id INTEGER,
				  rule_component_id INTEGER,
				  rule_component_parm_id INTEGER,
				  parm_value text  NULL,
				  PRIMARY KEY  (rule_set_id,rule_component_id,rule_component_parm_id)
				);
				
		CREATE TABLE company (
				  date_modified DATE NULL,
				  date_created DATE NULL,
				  active_status varchar(10),
				  company_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
				  name varchar(100) ,
				  name_short varchar(10) ,
				  co_entity_type varchar(100),
				  ecash_process_type varchar(1),
				  property_id INTEGER
				 
				);

		CREATE TABLE loan_type (
				  date_modified DATE NULL,
				  date_created DATE NULL,
				  active_status varchar(10),
				  company_id INTEGER,
				  loan_type_id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
				  name varchar(100) ,
				  name_short varchar(25) ,
				  abbreviation varchar(5) ,
				  UNIQUE  (company_id,name_short)
				);
