<?php 

/*
 * This file was automatically generated by generate_writable_model.php
 * at 2011-11-18, 09:40:13 from 'mysql:host=localhost;port=3306;dbname=ldb_mls'.
 *
 * NOTE: Modifications to this file will be overwritten if/when
 * it is regenerated.
 *
 */
class ECash_Models_NirvanaProcessLog extends ECash_Models_WritableModel  
{
	/**
	 * The list of columns this model contains
	 * @return array string[]
	 */
	public function getColumns()
	{
		static $columns = array(
			'date_modified', 'trigger_name', 'last_affected_date'
		);
		return $columns;
	}

	/**
	 * An array of the columns that comprise the primary key
	 * @return array string[]
	 */
	public function getPrimaryKey()
	{
		return array('trigger_name');
	}

	/**
	 * The auto increment column, if any
	 * @return string|void
	 */
	public function getAutoIncrement()
	{
		return NULL;
	}

	/**
	 * Indicates the table name
	 * @return string
	 */
	public function getTableName()
	{
		return 'nirvana_process_log';
	}

	/**
	 * Gets the column data for updating/insertion
	 *
	 * This is used to perform per-column transformations as the data goes into the database.
	 *
	 * @return array
	 */
	public function getColumnData()
	{
		$column_data = parent::getColumnData();
		$column_data['date_modified'] = date('Y-m-d H:i:s', $column_data['date_modified']);
		$column_data['last_affected_date'] = date('Y-m-d H:i:s', $column_data['last_affected_date']);
		return $column_data;
	}

	/**
	 * Sets the column data in the model
	 *
	 * This is used to perform per-column transformation as the data comes from the database
	 *
	 * @return void
	 */
	protected function setColumnData($column_data)
	{
		$column_data['date_modified'] = strtotime($column_data['date_modified']);
		$column_data['last_affected_date'] = strtotime($column_data['last_affected_date']);
		parent::setColumnData($column_data);
	}
}

?>