<?php

/*
 * This file was automatically generated by generate_writable_model.php
 * at 2009-02-05, 15:19:21 from 'mysql:host=db117.ept.tss;port=3306;dbname=ldb_occ'.
 *
 * NOTE: Modifications to this file will be overwritten if/when
 * it is regenerated.
 *
 */
class ECash_Models_Reference_EventlogEvent extends ECash_Models_WritableModel implements DB_Models_IReferenceModel_1
{
	/**
	 * The list of columns this model contains
	 * @return array string[]
	 */
	public function getColumns()
	{
		static $columns = array(
			'eventlog_event_id', 'name_short'
		);
		return $columns;
	}

	public function getColumnID()
	{
		return 'eventlog_event_id';
	}

	public function getColumnName()
	{
		return 'name_short';
	}

	/**
	 * An array of the columns that comprise the primary key
	 * @return array string[]
	 */
	public function getPrimaryKey()
	{
		return array('eventlog_event_id');
	}

	/**
	 * The auto increment column, if any
	 * @return string|void
	 */
	public function getAutoIncrement()
	{
		return 'eventlog_event_id';
	}

	/**
	 * Indicates the table name
	 * @return string
	 */
	public function getTableName()
	{
		return 'eventlog_event';
	}

}

 ?>